<template>
  <view class="page">
    <view v-if="loading" class="empty">工作台加载中</view>
    <block v-else-if="data">
      <view class="head"><text class="name">{{ data.employee.name }}</text><text class="role">{{ typeText }}</text><text class="sub">订单履约与到店服务</text></view>
      <view class="tabs"><view v-if="data.can_sales" :class="['tab',{active:active==='sales'}]" @click="switchTab('sales')">租赁履约</view><view v-if="data.can_service" :class="['tab',{active:active==='service'}]" @click="switchTab('service')">服务核销</view></view>
      <block v-if="active==='sales'"><view class="section-head"><text>待交车订单池</text><text>{{ rental.pool.length }} 单</text></view><view v-if="!rental.pool.length" class="empty small">暂无待交车订单</view><view v-for="item in rental.pool" :key="item.id" class="task"><view><text class="title">{{ item.car_name }} · {{ item.plate_no }}</text><text>订单 {{ item.order_no }}</text><text>取车 {{ item.pickup_time }}</text></view><button class="mini-btn" @click="claim(item)">认领交车</button></view><view class="section-head"><text>我的履约订单</text><text>{{ rental.mine.length }} 单</text></view><view v-if="!rental.mine.length" class="empty small">认领后会显示在这里</view><view v-for="item in rental.mine" :key="item.id" class="task" @click="openRental(item)"><view><text class="title">{{ item.car_name }} · {{ item.plate_no }}</text><text>{{ item.status_text }} · {{ item.order_no }}</text><text>{{ item.status==='pending_pickup'?'取车':'还车' }}时间 {{ item.status==='pending_pickup'?item.pickup_time:item.return_time }}</text></view><text class="chevron">›</text></view></block>
      <block v-else><view class="section-head"><text>待报价订单</text><text>{{ service.quotes?.length || 0 }} 单</text></view><view v-if="!(service.quotes||[]).length" class="empty small">暂无待报价订单</view><view v-for="item in service.quotes" :key="item.id" class="task" @click="openQuote(item)"><view><text class="title">{{ item.service_item_name }}</text><text>{{ item.service_plate_no }} · {{ item.order_no }}</text><text>{{ item.status==='pending_price_confirmation'?'已报价，等待用户确认':'待现场报价' }}</text></view><text class="chevron">›</text></view><view class="scan-card" @click="scan"><text class="scan-icon">□</text><view><text class="scan-title">扫码核销服务订单</text><text class="scan-note">扫描客户展示的服务订单核销码</text></view></view><view class="section-head"><text>我的服务订单</text><text>{{ service.mine.length }} 单</text></view><view v-if="!service.mine.length" class="empty small">扫码核销后会显示在这里</view><view v-for="item in service.mine" :key="item.id" class="task" @click="openService(item)"><view><text class="title">{{ item.service_item_name }}</text><text>{{ item.service_plate_no }} · {{ item.order_no }}</text><text>{{ item.status==='processing'?'服务进行中':'已完成' }}</text></view><text class="chevron">›</text></view></block>
    </block>
    <view v-else class="empty">当前账号未关联员工档案</view>
  </view>
</template>
<script setup>
import { computed, ref } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import { claimRental, getEmployeeWorkbench, getRentalTasks, getServiceTasks, verifyServiceOrder } from '../../api/employee'
const data=ref(null), rental=ref({pool:[],mine:[]}), service=ref({pool:[],mine:[]}), loading=ref(true), active=ref('sales')
const typeText=computed(()=>({sales:'销售员工',service:'服务员工',mixed:'综合员工',admin:'管理员'}[data.value?.employee?.employee_type]||'员工'))
const load=async()=>{loading.value=true;try{const result=await getEmployeeWorkbench();data.value=result.data;if(!data.value.can_sales)active.value='service';await loadTasks()}catch(e){data.value=null;uni.showToast({title:e.msg||'工作台读取失败',icon:'none'})}finally{loading.value=false}}
const loadTasks=async()=>{try{if(active.value==='sales')rental.value=(await getRentalTasks()).data||{pool:[],mine:[]};else service.value=(await getServiceTasks()).data||{pool:[],mine:[]}}catch(e){uni.showToast({title:e.msg||'订单读取失败',icon:'none'})}}
const switchTab=async tab=>{active.value=tab;await loadTasks()}
const claim=item=>uni.showModal({title:'认领交车',content:`确认认领订单 ${item.order_no} 吗？认领后由你负责交车和还车验车。`,success:async({confirm})=>{if(!confirm)return;try{await claimRental(item.id);uni.showToast({title:'认领成功',icon:'success'});loadTasks()}catch(e){uni.showToast({title:e.msg||'认领失败',icon:'none'})}}})
const openRental=item=>{if(['pending_check','pending_settlement'].includes(item.status))return uni.showToast({title:'当前正在等待用户确认',icon:'none'});uni.navigateTo({url:`/pages/employee/rental-inspection?id=${item.id}&type=${item.status==='pending_pickup'?'pickup':'return'}&name=${encodeURIComponent(item.car_name||'')}&plate=${encodeURIComponent(item.plate_no||'')}`})}
const openService=item=>uni.navigateTo({url:`/pages/employee/service-perform?id=${item.id}&name=${encodeURIComponent(item.service_item_name||'')}&plate=${encodeURIComponent(item.service_plate_no||'')}`})
const openQuote=item=>uni.navigateTo({url:`/pages/employee/service-quote?id=${item.id}&name=${encodeURIComponent(item.service_item_name||'')}&plate=${encodeURIComponent(item.service_plate_no||'')}&min=${item.price_min_snapshot||0}&max=${item.price_max_snapshot||0}&previous=${item.payable_amount||0}`})
const scan=()=>uni.scanCode({onlyFromCamera:false,success:async({result})=>{try{const d=await verifyServiceOrder(result);uni.showToast({title:'核销成功',icon:'success'});setTimeout(()=>openService(d.data),400)}catch(e){uni.showToast({title:e.msg||'核销失败',icon:'none'})}} ,fail:()=>{}})
onShow(load)
</script>
<style scoped>
.page{min-height:100vh;padding:24rpx 28rpx 70rpx;background:#f5f7fa}.head{padding:30rpx;border-radius:8rpx;background:#1f2937;color:#fff}.name{display:block;font-size:36rpx;font-weight:700}.role{display:inline-block;margin-top:12rpx;padding:4rpx 12rpx;border-radius:4rpx;background:#334155;font-size:22rpx}.sub{display:block;margin-top:12rpx;color:#cbd5e1;font-size:23rpx}.tabs{display:flex;margin:20rpx 0;background:#fff;border-radius:8rpx}.tab{flex:1;padding:24rpx 0;color:#64748b;text-align:center;font-size:28rpx}.tab.active{color:#1677ff;font-weight:700;border-bottom:4rpx solid #1677ff}.section-head{display:flex;justify-content:space-between;margin-top:28rpx;color:#374151;font-size:28rpx;font-weight:700}.section-head text:last-child{color:#94a3b8;font-size:22rpx;font-weight:400}.task,.scan-card{display:flex;align-items:center;justify-content:space-between;margin-top:16rpx;padding:24rpx;border-radius:8rpx;background:#fff}.task view{display:flex;flex:1;flex-direction:column;gap:8rpx;color:#64748b;font-size:22rpx}.task .title{color:#1f2937;font-size:29rpx;font-weight:700}.mini-btn{margin:0;background:#1677ff;color:#fff;font-size:22rpx}.chevron{color:#94a3b8;font-size:42rpx}.scan-card{gap:20rpx;background:#eff6ff}.scan-icon{display:flex;align-items:center;justify-content:center;width:72rpx;height:72rpx;border:4rpx solid #1677ff;color:#1677ff;font-size:44rpx}.scan-title{display:block;color:#1e3a8a;font-size:29rpx;font-weight:700}.scan-note{display:block;margin-top:8rpx;color:#64748b;font-size:22rpx}.empty{padding:150rpx 20rpx;color:#94a3b8;text-align:center;font-size:26rpx}.empty.small{padding:45rpx 20rpx;background:#fff;border-radius:8rpx}
</style>
