<template><view class="page"><view class="head"><text class="title">{{ name }}</text><text>{{ plate }} · {{ rangeText }}</text><text v-if="previous>0">当前应付 ¥{{ previous.toFixed(2) }}</text></view><view class="card"><text class="label">本次报价</text><input v-model="amount" type="digit" placeholder="请输入实际服务金额"/><text class="label">报价说明</text><textarea v-model.trim="reason" maxlength="500" placeholder="说明损坏情况、施工范围、材料或补款原因"/></view><button class="submit" :loading="submitting" @click="submit">提交报价，等待用户确认</button></view></template>
<script setup>
import { computed, ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import { quoteServiceOrder } from '../../api/employee'
const id=ref(0),name=ref('汽车服务'),plate=ref(''),min=ref(0),max=ref(0),previous=ref(0),amount=ref(''),reason=ref(''),submitting=ref(false)
const rangeText=computed(()=>min.value||max.value?`参考区间 ¥${min.value||0}-${max.value||'不限'}`:'现场勘验后报价')
onLoad(q=>{id.value=Number(q.id||0);name.value=decodeURIComponent(q.name||'汽车服务');plate.value=decodeURIComponent(q.plate||'');min.value=Number(q.min||0);max.value=Number(q.max||0);previous.value=Number(q.previous||0);amount.value=previous.value?previous.value.toFixed(2):''})
const submit=async()=>{if(Number(amount.value)<=0||!reason.value)return uni.showToast({title:'请填写报价和报价说明',icon:'none'});submitting.value=true;try{await quoteServiceOrder(id.value,{quoted_amount:amount.value,reason:reason.value});uni.showToast({title:'报价已提交',icon:'success'});setTimeout(()=>uni.navigateBack(),600)}catch(e){uni.showToast({title:e.msg||'报价提交失败',icon:'none'})}finally{submitting.value=false}}
</script><style scoped>.page{min-height:100vh;padding:24rpx 28rpx;background:#f5f7fa}.head,.card{padding:28rpx;border-radius:8rpx;background:#fff}.head{display:flex;flex-direction:column;gap:12rpx;color:#64748b;font-size:24rpx}.title{color:#1f2937;font-size:36rpx;font-weight:700}.card{margin-top:20rpx}.label{display:block;margin-top:22rpx;color:#374151;font-size:25rpx;font-weight:600}.label:first-child{margin-top:0}input,textarea{box-sizing:border-box;width:100%;margin-top:12rpx;padding:18rpx;border:1rpx solid #dbe3ef;border-radius:6rpx;background:#f8fafc;color:#1f2937;font-size:26rpx}input{height:82rpx}textarea{height:180rpx}.submit{margin-top:28rpx;border-radius:8rpx;background:#1677ff;color:#fff;font-size:30rpx}</style>
