<template>
  <view class="page"><view class="card"><text class="title">补充评价</text><text class="note">商家已回复您的评价，您可以补充一次后续体验。</text><textarea v-model.trim="content" class="content-input" maxlength="500" placeholder="补充您的后续体验，最多500字"/><text class="counter">{{ content.length }}/500</text><view class="image-list"><view v-for="(image,index) in images" :key="image" class="image-item"><image :src="image" mode="aspectFill"/><text class="remove" @click="images.splice(index,1)">×</text></view><view v-if="images.length<9" class="image-add" @click="chooseImage">+</view></view></view><button class="submit-button" :loading="submitting" @click="submit">提交补充评价</button></view>
</template>
<script setup>
import { ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import { followUpOrderReview, uploadOrderReviewImage } from '../../api/review'
const reviewId=ref(0),content=ref(''),images=ref([]),submitting=ref(false)
const chooseImage=()=>uni.chooseImage({count:9-images.value.length,sizeType:['compressed'],success:async({tempFilePaths})=>{uni.showLoading({title:'上传中',mask:true});try{for(const filePath of tempFilePaths){const url=await uploadOrderReviewImage(filePath);if(url)images.value.push(url)}}catch(error){uni.showToast({title:error.msg||'图片上传失败',icon:'none'})}finally{uni.hideLoading()}}})
const submit=async()=>{if(!content.value)return uni.showToast({title:'请填写补充内容',icon:'none'});submitting.value=true;try{await followUpOrderReview(reviewId.value,{content:content.value,images:JSON.stringify(images.value)});uni.showToast({title:'补充评价已提交',icon:'success'});setTimeout(()=>uni.navigateBack(),700)}catch(error){uni.showToast({title:error.msg||'提交失败',icon:'none'})}finally{submitting.value=false}}
onLoad(({id})=>{reviewId.value=Number(id)})
</script>
<style scoped>.page{min-height:100vh;padding:24rpx 32rpx calc(56rpx + env(safe-area-inset-bottom))}.card{padding:26rpx;border-radius:8rpx;background:#fff}.title,.note{display:block}.title{color:#1f2937;font-size:34rpx;font-weight:700}.note{margin-top:10rpx;color:#6b7280;font-size:23rpx;line-height:1.5}.content-input{box-sizing:border-box;width:100%;height:240rpx;margin-top:22rpx;color:#374151;font-size:27rpx;line-height:1.55}.counter{display:block;color:#9ca3af;font-size:21rpx;text-align:right}.image-list{display:flex;flex-wrap:wrap;gap:14rpx;margin-top:16rpx}.image-item,.image-add{position:relative;display:flex;align-items:center;justify-content:center;width:142rpx;height:142rpx;overflow:hidden;border-radius:6rpx}.image-item image{width:100%;height:100%}.image-add{border:1rpx dashed #9ca3af;color:#6b7280;font-size:52rpx}.remove{position:absolute;top:6rpx;right:6rpx;display:flex;align-items:center;justify-content:center;width:34rpx;height:34rpx;border-radius:50%;background:rgba(31,41,55,.7);color:#fff;font-size:24rpx}.submit-button{margin-top:28rpx;border-radius:6rpx;background:#1677ff;color:#fff;font-size:30rpx}</style>
