<template><view class="page"><view class="notice">{{ notice }}</view><button v-if="mode === 'contract' && contractUrl" class="contract-button" @click="openContract">查看电子合同</button><canvas class="signature" canvas-id="signatureCanvas" disable-scroll="true" @touchstart="start" @touchmove="move" @touchend="end"></canvas><view class="tools"><button class="clear" @click="clear">重写</button><button class="submit" @click="submit">确认并提交</button></view></view></template>
<script setup>
import { computed, nextTick, ref } from 'vue'
import { onLoad } from '@dcloudio/uni-app'
import { APP_CONFIG } from '../../config/app'
import { confirmRentalContract, confirmRentalInspection, confirmRentalSettlement } from '../../api/rental'
const mode=ref('inspection'), id=ref(0), orderId=ref(0), contractUrl=ref(''), contentHash=ref(''), inspectionType=ref('pickup'), drew=ref(false); let ctx; let last=null
const notice=computed(()=>mode.value==='contract'?'请先查看电子合同，再在签名区域内手写签名。提交即表示你已阅读并同意合同内容。':(mode.value==='inspection'&&inspectionType.value==='return'?'请核对还车验车单、照片证据和费用说明。提交签名即表示确认还车验车与本次结算；如有异议请返回订单提交异议。':'请核对交车验车单、照片证据和随车物品。提交签名后订单将进入租赁中。'))
onLoad(async q=>{mode.value=q.mode||'inspection';id.value=Number(q.id);orderId.value=Number(q.order_id);contractUrl.value=q.contract_url?decodeURIComponent(q.contract_url):'';contentHash.value=q.hash?decodeURIComponent(q.hash):'';inspectionType.value=q.inspection_type==='return'?'return':'pickup';await nextTick();ctx=uni.createCanvasContext('signatureCanvas');ctx.setStrokeStyle('#1f2937');ctx.setLineWidth(3);ctx.setLineCap('round');ctx.setLineJoin('round');ctx.draw()})
const point=e=>{const p=e.touches?.[0]||e.changedTouches?.[0];return {x:p.x,y:p.y}}
const start=e=>{last=point(e);ctx.beginPath();ctx.moveTo(last.x,last.y)}
const move=e=>{if(!last)return;const p=point(e);ctx.lineTo(p.x,p.y);ctx.stroke();ctx.draw(true);last=p;drew.value=true}
const end=()=>{last=null}
const clear=()=>{ctx.clearRect(0,0,700,420);ctx.draw();drew.value=false}
const upload=()=>new Promise((resolve,reject)=>uni.canvasToTempFilePath({canvasId:'signatureCanvas',success:r=>{const token=uni.getStorageSync('hax_user_token');uni.uploadFile({url:`${APP_CONFIG.apiBaseUrl}/rental/fulfillment/upload`,filePath:r.tempFilePath,name:'file',header:token?{Authorization:`Bearer ${token}`}:{},success:x=>{try{const d=JSON.parse(x.data);d.code===0?resolve(d.data.url):reject({msg:d.msg||'上传失败'})}catch{reject({msg:'签名上传失败'})}},fail:()=>reject({msg:'签名上传失败'})})},fail:()=>reject({msg:'签名生成失败'})}))
const openContract=()=>uni.downloadFile({url:contractUrl.value,success:r=>uni.openDocument({filePath:r.tempFilePath,showMenu:true}),fail:()=>uni.showToast({title:'合同下载失败',icon:'none'})})
const submit=async()=>{if(!drew.value)return uni.showToast({title:'请先完成签名',icon:'none'});try{uni.showLoading({title:'正在提交',mask:true});const signature=await upload();if(mode.value==='contract')await confirmRentalContract(id.value,{signature});else if(mode.value==='settlement')await confirmRentalSettlement(id.value,{signature});else await confirmRentalInspection(id.value,{signature,content_hash:contentHash.value});uni.hideLoading();uni.showToast({title:mode.value==='contract'?'合同签署成功':inspectionType.value==='return'?'还车确认成功':'交车确认成功',icon:'success'});setTimeout(()=>uni.navigateBack(),600)}catch(e){uni.hideLoading();uni.showToast({title:e.msg||'提交失败',icon:'none'})}}
</script><style scoped>.page{min-height:100vh;padding:32rpx;background:#f5f7fa}.notice{padding:24rpx;border-radius:8rpx;background:#fff;color:#5b6573;font-size:25rpx;line-height:1.6}.contract-button{margin-top:20rpx;border:1rpx solid #bcd7ff;background:#fff;color:#1677ff;font-size:25rpx}.signature{width:100%;height:420rpx;margin-top:28rpx;background:#fff;border:1rpx dashed #b6c3d4;border-radius:8rpx}.tools{display:flex;gap:20rpx;margin-top:28rpx}.tools button{flex:1;border-radius:8rpx;font-size:28rpx}.clear{border:1rpx solid #cbd5e1;background:#fff;color:#475569}.submit{background:#1677ff;color:#fff}</style>
