<template>
  <view class="page">
    <view v-if="loading" class="empty">行程加载中</view>
    <block v-else-if="itinerary">
      <view class="hero"><view><text class="title">{{ itinerary.name }}</text><text class="summary">{{ itinerary.start_date }} 至 {{ itinerary.end_date }} · {{ itinerary.day_count }} 天</text><text class="summary">全程约 {{ distanceText(itinerary.distance_meters) }} · 路途 {{ itinerary.duration_minutes }} 分钟 · 游玩 {{ totalStayMinutes }} 分钟</text><text class="summary">预计门票与餐饮 ¥{{ Number(itinerary.estimated_budget || 0).toFixed(2) }}</text></view><button class="share" open-type="share">分享</button></view>
      <scroll-view scroll-x class="day-tabs"><view class="tabs"><view v-for="day in itinerary.days" :key="day.id" class="tab" :class="{active:activeDayId===day.id}" @click="activeDayId=day.id">第 {{ day.day_no }} 天</view></view></scroll-view>
      <view v-if="activeDay" class="day-card"><view class="day-head"><text class="day-date">{{ activeDay.plan_date }} · {{ activeDay.day_start_time }}-{{ activeDay.day_end_time }}</text><text class="day-summary">路途 {{ activeDay.duration_minutes }} 分钟 · 停留 {{ dayStayMinutes }} 分钟 · 预计 ¥{{ dayBudget.toFixed(2) }}</text></view><view v-if="routePoints.length" class="route-panel"><map class="route-map" :latitude="mapCenter.latitude" :longitude="mapCenter.longitude" :markers="routeMarkers" :polyline="routePolylines" :include-points="routePoints" :scale="12" show-location="false"/><text class="route-tip">{{ activeDay.stops.length }} 个途径点，路线以当前日期为准</text></view><view v-if="!activeDay.stops.length" class="empty-day">当天暂无地点</view><view v-for="(stop,index) in activeDay.stops" :key="stop.id" class="stop"><view class="stop-index">{{ index+1 }}</view><view class="stop-main" @click="navigate(stop)"><text class="stop-time">{{ stop.start_time }}-{{ stop.end_time }} · 停留 {{ stop.duration_minutes || 0 }} 分钟</text><text class="stop-name">{{ stop.name }}</text><text class="stop-location">{{ stop.location || '地点位置待完善' }}</text><text v-if="Number(stop.estimated_cost)>0" class="stop-note">预计 ¥{{ Number(stop.estimated_cost).toFixed(2) }}</text><text v-if="stop.time_slot_text" class="stop-note">推荐时段 {{ stop.time_slot_text }}</text><text v-if="stop.schedule_conflict" class="conflict">当前顺序与每日时间有冲突</text></view><view class="actions"><text @click="moveOrder(index,-1)">上移</text><text @click="moveOrder(index,1)">下移</text><text @click="moveDay(stop,-1)">前日</text><text @click="moveDay(stop,1)">后日</text><text @click="replaceStop(stop)">替换</text></view></view></view>
      <view class="tips">可直接调整途径点顺序、日期或替换地点。预算仅按已录入的门票和人均消费估算，不含交通与住宿。</view><button class="delete-button" @click="remove">删除行程</button>
    </block><view v-else class="empty">行程不存在</view>
  </view>
</template>
<script setup>
import { computed, ref } from 'vue'
import { onLoad, onShareAppMessage } from '@dcloudio/uni-app'
import { deleteTravelItinerary, getTravelItinerary, getTravelItineraryTargets, moveTravelItineraryStop, reorderTravelItinerary, replaceTravelItineraryStop } from '../../api/travel'
const id=ref(0),itinerary=ref(null),activeDayId=ref(0),loading=ref(true)
const activeDay=computed(()=>itinerary.value?.days.find(day=>day.id===activeDayId.value)||itinerary.value?.days[0]||null)
const totalStayMinutes=computed(()=>Number(itinerary.value?.days?.flatMap(day=>day.stops||[]).reduce((sum,stop)=>sum+Number(stop.duration_minutes||0),0)||0))
const dayStayMinutes=computed(()=>Number(activeDay.value?.stops?.reduce((sum,stop)=>sum+Number(stop.duration_minutes||0),0)||0))
const dayBudget=computed(()=>Number(activeDay.value?.stops?.reduce((sum,stop)=>sum+Number(stop.estimated_cost||0),0)||0))
const routePoints=computed(()=>{const stops=activeDay.value?.stops||[];const points=[];const origin={latitude:Number(itinerary.value?.origin_latitude),longitude:Number(itinerary.value?.origin_longitude)};if(Number.isFinite(origin.latitude)&&Number.isFinite(origin.longitude))points.push(origin);stops.forEach(stop=>{const point={latitude:Number(stop.latitude),longitude:Number(stop.longitude)};if(Number.isFinite(point.latitude)&&Number.isFinite(point.longitude))points.push(point)});return points})
const routeMarkers=computed(()=>routePoints.value.map((point,index)=>({id:index,latitude:point.latitude,longitude:point.longitude,width:28,height:28,callout:{content:index===0?'起点':String(index),display:'ALWAYS',padding:4,borderRadius:12,bgColor:index===0?'#0f8e69':'#1677ff',color:'#ffffff',fontSize:11,textAlign:'center'} })))
const routePolylines=computed(()=>{const saved=activeDay.value?.route_data?.polyline||[];const points=saved.map(point=>({latitude:Number(point.latitude),longitude:Number(point.longitude)})).filter(point=>Number.isFinite(point.latitude)&&Number.isFinite(point.longitude));const path=points.length>=2?points:routePoints.value;return path.length>=2?[{points:path,color:'#1677ff',width:5,arrowLine:true,borderColor:'#ffffff',borderWidth:1}]:[]})
const mapCenter=computed(()=>routePoints.value[0]||{latitude:36.0671,longitude:120.3826})
const distanceText=value=>Number(value)>=1000?`${(Number(value)/1000).toFixed(1)} km`:`${value||0} m`
const load=async()=>{loading.value=true;try{itinerary.value=(await getTravelItinerary(id.value)).data||null;if(itinerary.value&&!itinerary.value.days.some(day=>day.id===activeDayId.value))activeDayId.value=itinerary.value.days[0]?.id||0}catch(error){uni.showToast({title:error.msg||'读取失败',icon:'none'})}finally{loading.value=false}}
const apply=payload=>{itinerary.value=payload;if(!itinerary.value.days.some(day=>day.id===activeDayId.value))activeDayId.value=itinerary.value.days[0]?.id||0}
const moveOrder=async(index,offset)=>{const day=activeDay.value,target=index+offset;if(!day||target<0||target>=day.stops.length)return;const ids=day.stops.map(item=>item.id);[ids[index],ids[target]]=[ids[target],ids[index]];try{apply((await reorderTravelItinerary(id.value,{day_id:day.id,stop_ids:ids})).data)}catch(error){uni.showToast({title:error.msg||'调整失败',icon:'none'})}}
const moveDay=async(stop,offset)=>{const target=activeDay.value.day_no+offset;if(target<1)return;try{apply((await moveTravelItineraryStop(id.value,{stop_id:stop.id,target_day_no:target})).data)}catch(error){uni.showToast({title:error.msg||'移动失败',icon:'none'})}}
const replaceStop=async(stop)=>{try{const result=await getTravelItineraryTargets();const targets=(result.data?.list||[]).filter(item=>!(item.target_type===stop.target_type&&Number(item.target_id)===Number(stop.target_id)));if(!targets.length)return uni.showToast({title:'暂无可替换地点',icon:'none'});const options=targets.slice(0,30);uni.showActionSheet({itemList:options.map(item=>`${item.type_name} · ${item.name}`),success:async({tapIndex})=>{try{apply((await replaceTravelItineraryStop(id.value,{stop_id:stop.id,target_type:options[tapIndex].target_type,target_id:options[tapIndex].target_id})).data);uni.showToast({title:'地点已替换',icon:'success'})}catch(error){uni.showToast({title:error.msg||'替换失败',icon:'none'})}}})}catch(error){uni.showToast({title:error.msg||'地点读取失败',icon:'none'})}}
const navigate=stop=>uni.openLocation({latitude:Number(stop.latitude),longitude:Number(stop.longitude),name:stop.name,address:stop.location||'',scale:16})
const remove=()=>uni.showModal({title:'删除行程',content:'删除后不可恢复，确认删除吗？',success:async result=>{if(!result.confirm)return;try{await deleteTravelItinerary(id.value);uni.navigateBack()}catch(error){uni.showToast({title:error.msg||'删除失败',icon:'none'})}}})
onShareAppMessage(()=>({title:itinerary.value?.name||'我的旅行计划',path:`/pages/travel/itinerary?id=${id.value}`}))
onLoad(options=>{id.value=Number(options.id||0);load()})
</script>
<style scoped>.page{min-height:100vh;padding:24rpx;background:#f5f7fa;box-sizing:border-box}.hero,.day-card{border-radius:8rpx;background:#fff}.hero{display:flex;justify-content:space-between;gap:20rpx;padding:26rpx}.title,.summary{display:block}.title{font-size:34rpx;font-weight:700;color:#1f2937}.summary{margin-top:10rpx;color:#66758a;font-size:23rpx}.share{flex:0 0 auto;margin:0;padding:0 20rpx;border:1rpx solid #bfdbfe;border-radius:6rpx;background:#fff;color:#1677ff;font-size:22rpx;line-height:60rpx}.day-tabs{margin:22rpx -24rpx 0;white-space:nowrap}.tabs{display:inline-flex;gap:14rpx;padding:0 24rpx}.tab{padding:16rpx 28rpx;border-radius:32rpx;background:#e9edf3;color:#66758a;font-size:24rpx}.tab.active{background:#1677ff;color:#fff}.day-card{margin-top:20rpx;padding:0 22rpx}.day-head{padding:22rpx 0}.day-date,.day-summary{display:block}.day-date{color:#0f8e69;font-size:24rpx;font-weight:600}.day-summary{margin-top:8rpx;color:#94a3b8;font-size:21rpx}.route-panel{padding:0 0 20rpx}.route-map{width:100%;height:380rpx;border-radius:8rpx}.route-tip{display:block;margin-top:10rpx;color:#64748b;font-size:21rpx}.stop{display:flex;gap:16rpx;padding:22rpx 0;border-top:1rpx solid #edf0f5}.stop-index{display:flex;align-items:center;justify-content:center;flex:0 0 auto;width:40rpx;height:40rpx;border-radius:50%;background:#1677ff;color:#fff;font-size:22rpx}.stop-main{display:flex;flex:1;flex-direction:column;min-width:0}.stop-time{color:#1677ff;font-size:22rpx}.stop-name{margin-top:5rpx;overflow:hidden;color:#1f2937;font-size:27rpx;font-weight:600;text-overflow:ellipsis;white-space:nowrap}.stop-location,.stop-note,.conflict{margin-top:7rpx;color:#8894a5;font-size:21rpx}.stop-note{color:#0f8e69}.conflict{color:#e9692c}.actions{display:flex;flex:0 0 62rpx;flex-direction:column;gap:8rpx;color:#1677ff;font-size:20rpx;text-align:right}.tips{margin:20rpx 6rpx;color:#94a3b8;font-size:21rpx;line-height:1.55}.empty,.empty-day{padding:100rpx 0;color:#94a3b8;text-align:center;font-size:25rpx}.empty-day{padding:50rpx 0}.delete-button{margin-top:18rpx;background:#fff;color:#e9692c;font-size:26rpx}.delete-button::after,.share::after{border:0}</style>
